GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/649bfc841fcb7c46fa3de9f1

###
POST http://localhost:3001/api/persons
Content-Type:application/json


    {
        "name":"Taja Turunen",
        "number":"09-8010-001 500"
    }